export const IMPORT_CARDS = 'CARDS/IMPORT_CARDS';
export const FILTER_INPUT_VALUE = 'FILTER/FILTER_INPUT_VALUE';
export const FILTER_SELECT_VALUE = 'FILTER/FILTER_SELECT_VALUE';
export const FAVORITES_GET_ITEM = 'FAVORITES/FAVORITES_GET_ITEM';